#------------------BUILD STAGE------------------

FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package.-lock.json* ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src

RUN npm run build

#----------------RUNTIME STAGE------------------

FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --only=production

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/index.js"]



